using System.Globalization;
using System.Text;
using LLMWorkGUI.Infrastructure.Storage;

namespace LLMWorkGUI.Infrastructure.StarCliProxy;

/// <summary>
/// Generates the star-cliproxy configuration file inside the run directory (outside the project
/// root). Secrets are never written to disk: they are only passed to the owned child process
/// environment, which satisfies the ${ADMIN_TOKEN} and ${PROXY_API_KEY} placeholders in the
/// configuration. Command lines and logs never contain secrets either.
/// </summary>
internal static class StarCliProxyConfigWriter
{
    public const string EnvironmentFileName = ".env";

    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    private static readonly IReadOnlyDictionary<string, ProviderTemplate> ProviderTemplates =
        new Dictionary<string, ProviderTemplate>(StringComparer.OrdinalIgnoreCase)
        {
            ["codex"] = new("codex", "gpt-5.5"),
            ["agy"] = new("agy", "antigravity")
        };

    public static async Task<string> WriteAsync(
        string runDirectory,
        string configFileName,
        string hostname,
        int port,
        IReadOnlyList<string> providerIds,
        string adminToken,
        string apiKey,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(runDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(configFileName);
        ArgumentException.ThrowIfNullOrWhiteSpace(hostname);
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(port);
        ArgumentNullException.ThrowIfNull(providerIds);
        ArgumentException.ThrowIfNullOrWhiteSpace(adminToken);
        ArgumentException.ThrowIfNullOrWhiteSpace(apiKey);

        Directory.CreateDirectory(runDirectory);

        var dataDirectory = Path.Combine(runDirectory, "data");
        Directory.CreateDirectory(dataDirectory);

        var databasePath = Path.Combine(dataDirectory, "cliproxy.db");
        var configPath = Path.Combine(runDirectory, configFileName);

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by LLMWorkGUI for a single managed account context (ADR-0007).");
        builder.AppendLine("server:");
        builder.AppendLine($"  host: {System.Text.Json.JsonSerializer.Serialize(hostname)}");
        builder.AppendLine($"  port: {port.ToString(CultureInfo.InvariantCulture)}");
        builder.AppendLine("auth:");
        builder.AppendLine("  enabled: true");
        builder.AppendLine("  admin_token: \"${ADMIN_TOKEN}\"");
        builder.AppendLine("  initial_keys:");
        builder.AppendLine("    - name: \"llmworkgui\"");
        builder.AppendLine("      key: \"${PROXY_API_KEY}\"");
        builder.AppendLine("database:");
        builder.AppendLine($"  path: \"{EscapeYaml(databasePath)}\"");
        builder.AppendLine("providers:");

        foreach (var providerId in providerIds)
        {
            var template = ProviderTemplates.TryGetValue(providerId, out var known)
                ? known
                : new ProviderTemplate(providerId, providerId);

            builder.AppendLine($"  {System.Text.Json.JsonSerializer.Serialize(providerId)}:");
            builder.AppendLine("    enabled: true");
            builder.AppendLine($"    cli_path: \"{EscapeYaml(template.CliPath)}\"");
            builder.AppendLine($"    default_model: \"{EscapeYaml(template.DefaultModel)}\"");
            builder.AppendLine("    max_concurrent: 5");
            builder.AppendLine("    timeout_ms: 300000");
        }

        builder.AppendLine("model_mappings: []");

        var environmentPath = Path.Combine(runDirectory, EnvironmentFileName);
        // Fail-closed: in .NET, File.Delete is a no-op if the file does not exist, but throws
        // (UnauthorizedAccessException, IOException) if the file exists and cannot be deleted,
        // aborting startup before config.yaml is written and before child launch.
        File.Delete(environmentPath);

        // Publish only after the full document is flushed to a temporary file in the same directory.
        // The path is then replaced, so it never contains a truncated rewrite of config.yaml.
        await AtomicFile.WriteAllBytesAsync(
                configPath,
                Utf8NoBom.GetBytes(builder.ToString()),
                cancellationToken,
                overwrite: true)
            .ConfigureAwait(false);

        return configPath;
    }

    private static string EscapeYaml(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);

    private sealed record ProviderTemplate(string CliPath, string DefaultModel);
}
